# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Deep Learning Platform 블로그
tagline:          'A Jekyll theme'
description:      'Deep Learning Application과 Platform에 대한 포스팅을 하는 블로그입니다.'
url:              https://nsh3389.github.io
baseurl:          /

author:
  name:           'shnoh'
  url:            https://nsh3389.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate]
