# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Deep Learning Platform
tagline:          'A Jekyll theme'
#description:      '.'
url:              https://nsh3389.github.io
baseurl:          /

author:
  name:           'shnoh'
  url:            https://nsh3389.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate]

disqus_shortname: shnoh
# // git add -A; git commit -m "test"; git push
