# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Deep Learning Platform
tagline:          'A Jekyll theme'
description:      'abc 가나다'
url:              https://nsh3389.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Soonhyun Noh'
  url:            https://nsh3389.github.io

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:             https://github.com/fongandrew/hydeout
